### ISSUE TITLE
[#1] 빠른 내역 추가 버튼이 Calendar 아래로 내려가 보이지 않음 + modal 창 깨짐

### ISSUE THREAD

**Issue by lee-JunR** [lee-JunR/KB_FinancialLedger#26]
### 설명:
빠른 내역 추가 버튼이 Calendar 컴포넌트 아래로 내려가 보이지 않으며 모달 ui가 깨지는 문제가 발생하고 있습니다. 이로 인해 사용자가 버튼을 클릭할 수 없으며, 기능 사용에 불편을 겪고 있습니다.

### 재현 단계:
Calendar 컴포넌트가 포함된 페이지로 이동합니다.
창의 width가 991px 이하로 설정합니다.
빠른 내역 추가 버튼을 확인합니다.
버튼이 Calendar 아래로 내려가 보이지 않는 것을 확인합니다.
예상 동작:
빠른 내역 추가 버튼이 Calendar 컴포넌트 위에 위치하여 사용자가 쉽게 클릭할 수 있어야 합니다.
991px 이하의 상태에서 빠른내역 추가 버튼과 modal창의 버튼의 UI가 깨집니다.

### 실제 동작:
빠른 내역 추가 버튼이 Calendar 컴포넌트 아래로 내려가 보이지 않음.

### 스크린샷:
![image](https://github.com/lee-JunR/KB_FinancialLedger/assets/68640939/be48dafe-b945-418d-a06b-e1973bd3575e)
![image](https://github.com/lee-JunR/KB_FinancialLedger/assets/68640939/1763628c-6695-4b4b-b786-0c71c44a7a2d)

**Comment by doeun0509** [comment]
수정되었습니다
