### ISSUE TITLE
[#2] account 테이블 기본키 관련

### ISSUE THREAD

**Issue by lee-JunR** [lee-JunR/KB_FinancialLedger#38]
### 설명:

회원가입시 생성되는 account 테이블의 기본키가 index가 아닌 이름으로 생성됩니다.

### 재현 단계:

1. `/login` 에서 회원가입을 합니다
2. 회원가입이 진행되면 생기는 계정 account 테이블에 기본키가 회원가입시 생성했던 `userid`로 들어오는걸 확인합니다.

### 실제 동작:

```java
[
  {
    "total_income": 1664637,
    "total_expand": 317649,
    "profit": 1346988,
    "id": "1"
  },
  {
    "total_income": 446237,
    "total_expand": 236612,
    "profit": 209625,
    "id": "2"
  },
  {
    "id": "3",
    "total_income": 0,
    "total_expand": 0,
    "profit": 0
  },
  {
    "id": "4", // 이부분이 수정되어야함.
    "total_income": 0,
    "total_expand": 0,
    "profit": 0
  },
  {
```

### 스크린샷:

<img width="738" alt="image" src="https://github.com/lee-JunR/KB_FinancialLedger/assets/68640939/617f93fc-a3ec-4f26-8b7c-063f7f949898">

**Comment by HwanheeMoon** [comment]
`  const sendData = {
        "total_income" : 0,
        "total_expand" : 0,
        "profit" : 0,
        "id" : data.userId
    };`
